export const IPC_CHANNELS = {
  FOLDERS_ADD: 'folders:add',
  FOLDERS_ADD_GIT_REPOSITORIES: 'folders:addGitRepositories',
  FOLDERS_LIST: 'folders:list',
  FOLDERS_REMOVE: 'folders:remove',
  FOLDERS_GET_RULES: 'folders:getRules',
  FOLDERS_SET_RULES: 'folders:setRules',
  FOLDERS_GET_DUPLICATE_MIN_LINES: 'folders:getDuplicateMinLines',
  FOLDERS_SET_DUPLICATE_MIN_LINES: 'folders:setDuplicateMinLines',
  FOLDERS_GET_DUPLICATE_RULES: 'folders:getDuplicateRules',
  FOLDERS_SET_DUPLICATE_RULES: 'folders:setDuplicateRules',
  FOLDERS_PICK_DIRECTORY: 'folders:pickDirectory',
  SCAN_RUN: 'scan:run',
  SCAN_CANCEL: 'scan:cancel',
  SCAN_PROGRESS: 'scan:progress',
  SETTINGS_GET_GLOBAL_RULES: 'settings:getGlobalRules',
  SETTINGS_SET_GLOBAL_RULES: 'settings:setGlobalRules',
  STATS_SUMMARY: 'stats:summary',
  STATS_TREE: 'stats:tree',
  STATS_TOP_FILES: 'stats:topFiles',
  STATS_TOP_FUNCTIONS: 'stats:topFunctions',
  STATS_API_ROUTES: 'stats:apiRoutes',
  STATS_FILE_RELATIONS: 'stats:fileRelations',
  STATS_LARAVEL_SCHEMA: 'stats:laravelSchema',
  STATS_TAGS: 'stats:tags',
  STATS_FILE_TAGS: 'stats:fileTags',
  STATS_HEATMAP: 'stats:heatmap',
  STATS_DUPLICATES: 'stats:duplicates',
  FILE_READ: 'file:read',
  FILE_WRITE: 'file:write',
  FILE_META: 'file:meta',
  GIT_FILE_INFO: 'git:fileInfo',
  GIT_REPO_INFO: 'git:repoInfo',
  SYSTEM_SHOW_TREE_NODE_CONTEXT_MENU: 'system:showTreeNodeContextMenu',
  SYSTEM_OPEN_EXTERNAL: 'system:openExternal',
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
